name: Build on Tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore McduDcsBiosBridge.sln

      - name: Build
        run: dotnet build McduDcsBiosBridge.sln --configuration Release

      - name: Publish
        run: dotnet publish WWCduDcsBiosBridge.csproj --configuration Release --output ./publish